import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/swiper.min.css";
import "swiper/components/pagination/pagination.min.css";

export async function getStaticProps() {
  const res = await fetch(
    "https://raw.githubusercontent.com/fervillalbag/storymbaembo/main/api.json"
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Story Mbaembo</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Swiper
        direction="vertical"
        pagination={{ clickable: true }}
        className="mySwiper"
      >
        {data &&
          data.map((item) => (
            <SwiperSlide className="item" key={item.id}>
              <Swiper navigation={true} className="mySwiper">
                {item.images.map((image) => (
                  <SwiperSlide key={image.id}>
                    <img src={image.url} />
                  </SwiperSlide>
                ))}
              </Swiper>
            </SwiperSlide>
          ))}
      </Swiper>
    </div>
  );
}
