import Head from "next/head";
import Image from "next/image";
import { Swiper, SwiperSlide } from "swiper/react";
import SwiperCore, { Pagination } from "swiper/core";
import "swiper/swiper.min.css";
import "swiper/components/pagination/pagination.min.css";
import { useState } from "react";

export async function getStaticProps() {
  const res = await fetch(
    "https://raw.githubusercontent.com/fervillalbag/storymbaembo/main/api.json"
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const [swiperRef, setSwiperRef] = useState(null);
  SwiperCore.use([Pagination]);

  const slideTo = (index) => {
    swiperRef.slideTo(index - 1, 0);
  };

  return (
    <div>
      <Head>
        <title>Story Mbaembo</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Swiper
        direction="vertical"
        pagination={{ clickable: true }}
        className="mySwiper"
      >
        {data &&
          data.map((item) => (
            <SwiperSlide className="item" key={item.id}>
              <Swiper
                onSwiper={setSwiperRef}
                onSlideChange={() => slideTo(0)}
                navigation={true}
                className="mySwiper"
              >
                {item.images.map((image) => (
                  <SwiperSlide key={image.id}>
                    <Image
                      src={image.url}
                      alt={`Image ${image.id}`}
                      layout="fill"
                    />
                  </SwiperSlide>
                ))}
              </Swiper>
            </SwiperSlide>
          ))}
      </Swiper>
    </div>
  );
}
